# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 806)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1151, 761))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_depart = Depart()
        self.page_depart.setObjectName("page_depart")
        self.stackedWidget.addWidget(self.page_depart)
        self.page_zscore = ZScore()
        self.page_zscore.setObjectName("page_zscore")
        self.stackedWidget.addWidget(self.page_zscore)
        self.page_ga = GA()
        self.page_ga.setObjectName("page_ga")
        self.stackedWidget.addWidget(self.page_ga)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1220, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menu_abd = QtWidgets.QAction(MainWindow)
        self.menu_abd.setObjectName("menu_abd")
        self.menu_ob = QtWidgets.QAction(MainWindow)
        self.menu_ob.setObjectName("menu_ob")
        self.menu_gyn = QtWidgets.QAction(MainWindow)
        self.menu_gyn.setObjectName("menu_gyn")
        self.menu_card = QtWidgets.QAction(MainWindow)
        self.menu_card.setObjectName("menu_card")
        self.menu_vas = QtWidgets.QAction(MainWindow)
        self.menu_vas.setObjectName("menu_vas")
        self.menu_uro = QtWidgets.QAction(MainWindow)
        self.menu_uro.setObjectName("menu_uro")
        self.menu_smp = QtWidgets.QAction(MainWindow)
        self.menu_smp.setObjectName("menu_smp")
        self.menu_ped = QtWidgets.QAction(MainWindow)
        self.menu_ped.setObjectName("menu_ped")
        self.menu_zscore = QtWidgets.QAction(MainWindow)
        self.menu_zscore.setObjectName("menu_zscore")
        self.menu_ga = QtWidgets.QAction(MainWindow)
        self.menu_ga.setObjectName("menu_ga")
        self.menu_depart = QtWidgets.QAction(MainWindow)
        self.menu_depart.setObjectName("menu_depart")
        self.menu.addAction(self.menu_depart)
        self.menu_2.addAction(self.menu_zscore)
        self.menu_2.addAction(self.menu_ga)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", " 科室测量 "))
        self.menu_2.setTitle(_translate("MainWindow", " 特殊测量 "))
        self.menu_abd.setText(_translate("MainWindow", "腹部"))
        self.menu_ob.setText(_translate("MainWindow", "产科"))
        self.menu_gyn.setText(_translate("MainWindow", "妇科"))
        self.menu_card.setText(_translate("MainWindow", "心脏"))
        self.menu_vas.setText(_translate("MainWindow", "血管"))
        self.menu_uro.setText(_translate("MainWindow", "泌尿"))
        self.menu_smp.setText(_translate("MainWindow", "小器官"))
        self.menu_ped.setText(_translate("MainWindow", "儿科"))
        self.menu_zscore.setText(_translate("MainWindow", "心脏Z评分"))
        self.menu_ga.setText(_translate("MainWindow", "产科孕龄"))
        self.menu_depart.setText(_translate("MainWindow", "科室测量"))
from depart.Card import ZScore
from depart.Depart import Depart
from depart.Ob import GA
