# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zscore.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1032, 573)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1001, 521))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_card = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tab_card.setFont(font)
        self.tab_card.setObjectName("tab_card")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_card)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 10, 971, 471))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2008 = QtWidgets.QWidget()
        self.tab_2008.setObjectName("tab_2008")
        self.tabWidget_2.addTab(self.tab_2008, "")
        self.tab_2013 = QtWidgets.QWidget()
        self.tab_2013.setObjectName("tab_2013")
        self.tabWidget_2.addTab(self.tab_2013, "")
        self.tabWidget.addTab(self.tab_card, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2008), _translate("Form", "Bei xia 2008"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2013), _translate("Form", "Pattern 2013"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_card), _translate("Form", "Z评分"))
